config/routes.rb
Rails.application.routes.draw do
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'items#index'

  get 'carts/register'
  get 'carts/delete_all'
  post 'carts/:item_id/add_item' => 'carts#add_item', as: :carts_add_item #item_idをurlに含めて送信
  patch 'carts/:item_id/update_item' => 'carts#update_item', as: :carts_update_item
  delete 'carts/:item_id/delete_item' => 'carts#delete_item', as: :carts_delete_item
  # get 'carts/confirmation'
  get 'artists/admin_index'
  # get 'items/admin_index'
  patch 'users/:id/favorite' => 'users#favorite', as: :user_favorite
  # get 'purchase/:purchase_id/confirmation' => 'purchase_datails#confirmation', as: :confirmation

  resources :users, only: [:show, :edit, :update, :index, :destroy]do
    resources :addresses, only: [:new, :create, :edit, :show, :update, :destroy]
    resource :carts, only: [:show]
  end

  delete '/users/:id' => 'users#destroy'

  resources :artists

  resources :items do
    resource :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    resources :disks, only: [:new, :create, :index, :destroy]do
      resources :songs, only: [:new, :create, :edit, :update, :index, :destroy]
    end
  end

  resources :purchases, only: [:create, :update, :index]do
    resource :purchase_datails, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :reviews, dependent: :destroy
   has_many :likes, dependent: :destroy
   has_one :cart, dependent: :destroy
   has_many :addresses, dependent: :destroy
   has_many :purchases, dependent: :destroy
   belongs_to :artist, optional: true
   belongs_to :purchase, optional: true

    validates :last_name,
    presence: true

    validates :first_name,
    presence: true

    validates :last_name_kana,
    presence: true

    validates :first_name_kana,
    presence: true

    validates :phone_number,
    presence: true, numericality: { only_integer: true }

    validates :email,
    presence: true, uniqueness: true

    # validates :password,
    # # presence: true,
    # # uniqueness: true,
    # # length: { minimum: 6 },
    # format: { with: /\A[a-z0-9]+\z/i }

    scope :get_by_last_name, ->(last_name) { where("last_name like ?", "%#{last_name}%") }
    scope :get_by_first_name, ->(first_name) { where("first_name like ?", "%#{first_name}%") }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # def new
  # end

  # def create
  # end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :reset_session_url!, only:[:show, :edit]
  before_action :cart_destroy!, only: [:destroy]

  def show
    @user = User.find(params[:id])
    @review = Review.new
    unless @user.artist_id.nil?
      @artist = @user.artist
      @item = Item.where(artist_id: @artist.id).limit(1).order('created_at desc')
    end
    @genre = Genre.limit(1).order('created_at desc')
    @purchases = @user.purchases
    @rank = Item.find(Like.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
    @cart_item =CartItem.new
    unless admin_signed_in?
      if user_signed_in?
          if current_user.last_sign_in_at == current_user.current_sign_in_at
            if Address.exists?(user_id: current_user.id)
              unless session[:url].blank?
                redirect_to session[:url] and return
              end
            else
              redirect_to new_user_address_path(current_user)
              flash[:notice]="住所を登録して下さい" and return
            end
          end
          if @user.id != current_user.id
            redirect_to user_path(current_user) and return
          end
      else
      redirect_to new_user_session_path and return
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    unless admin_signed_in?
      if user_signed_in?
        if current_user.last_sign_in_at == current_user.current_sign_in_at
          unless Address.exists?(user_id: current_user.id)
            redirect_to new_user_address_path(current_user)
            flash[:notice]="住所を登録して下さい" and return
          end
        end
        if @user.id != current_user.id
          redirect_to edit_user_path(current_user) and return
        end
      else
        redirect_to new_user_session_path and return
      end
    end
  end

  def update
   user = User.find(params[:id])
    unless admin_signed_in?
      unless user_signed_in?
        redirect_to new_user_session_path and return
      end
    end
    if user.update(user_params)
      redirect_to user_path(user)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    if admin_signed_in?
      user.destroy
      redirect_to users_path
    else
      if user_signed_in?
        user.destroy
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end
  end

  def favorite
    if admin_signed_in?
      redirect_to artists_path
      flash[:alert]="管理者はお気に入り出来ません"
    else
      if user_signed_in?
        @artist = Artist.find(params[:id])
        @user = current_user
        if @user.artist_id == @artist.id
        # 現在のアーティストIDと登録したいIDが同じ時にnilにしてupdateする
          @user.artist_id = nil
          @user.update(artist_id: nil)
          # artist_id:にnilを入れてupdate
          redirect_to artist_path(@artist.id)
        else
          @user.update(artist_id: @artist.id)
          # artist_id:に@artist.id(参照してきたid)を入れてupdate
          redirect_to artist_path(@artist.id)
          flash[:notice]="お気に入りに登録しました！"
        end
      end
    end
  end

  def index
    @users = User.all
    @rank = Item.find(Like.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
    # group(:item_id)で、アイテムの番号が同じものにグループを分ける
    # order('count(item_id) desc')で、番号の多い順に並び替える
    # limit()で、表示する最大数を指定して
    # pluck(:item_id)で:item_idカラムのみを取り出すように指定。
    # Item.find(integer)最終的に、取り出される数値オブジェクトをアイテムのIDとすることで表示される
    if admin_signed_in?
      if params[:last_name].present?
        @users = @users.get_by_last_name params[:last_name]
      end
      if params[:first_name].present?
        @users = @users.get_by_first_name params[:first_name]
      end
      unless @users.count == User.all.count
      # @usersの数がUser.allから変わっているか確認する
        if @users.count == 0
        # usersの数が０の時
          @users = User.all
          flash.now[:notice] = "ヒットしませんでした。検索ワードを変えてみて下さい。"
          render :action => :index, layout: "user_index" and return
          # renderにする事で変更された情報を維持しつつnoticeを表示させる
        elsif @users.count > 0
          flash.now[:notice] = "#{@users.count}件のユーザーがヒットしました。"
          #{@users.count}で絞り込まれた数を表示させる
          render :action => :index, layout: "user_index" and return
          # renderにする事で変更された情報を維持しつつnoticeを表示させる
        end
      end
      render :index, layout: "user_index" and return
    else
      redirect_to root_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:phone_number,:email,:artist_id)
    end

    def reset_session_url!
      session[:url] = nil
    end

    def cart_destroy!
      cart = Cart.find_by(user_id: current_user)
      unless cart.nil? #cartがnilでなければ(つまりcartが存在していれば)
        if cart.cart_items.nil? #カートの中は空ですか？空ならカート消しても良いからdestroy
          cart.destroy
        else
          redirect_to user_path(current_user)
          flash[:alert]="あなたのカートに商品が存在しています。退会する前に確認して下さい。"
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="users_signup">

<h4><strong> 登録情報変更 </strong></h4>

<%#= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%#= devise_error_messages! %>
<%= form_for(@user) do |f| %>

  <div class="field">
    <p> 名前（漢字） </p>
    <span> 姓 </span>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", placeholder: "姓" %>
    <span> 名 </span>
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", placeholder: "名" %>
  </div>

  <div class="field">
    <p> 名前フリガナ（全角カナ） </p>
    <span> セイ </span>
    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", placeholder: "セイ" %>
    <span> メイ </span>
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", placeholder: "メイ" %>
  </div>

  <div class="field">
    <p> 電話番号（半角・ハイフン無し） </p>
    <%= f.number_field :phone_number, autofocus: true, autocomplete: "phone_number" %>
  </div>

  <div class="field">
    <p> メールアドレス </p>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <div> パスワード（半角英数字6桁以上） </div>
    <%# if @minimum_password_length %>
    <!-- <em>(<%#= @minimum_password_length %> characters minimum)</em>
    <%# end %> -->
    <%= f.text_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <p> パスワード確認 </p>
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <!-- <input type="submit" class="btn btn-danger" value="上記の内容で変更する" data-disable-with="上記の内容で変更する"> -->
    <%= f.submit "上記の内容で変更する", class:"btn btn-danger" %>
  </div>
<% end %>
  <div class="actions">
    <%#= link_to "住所変更及び新しい住所を登録する", user_address_path(current_user,current_user.addresses.first), class: 'btn btn-primary' %>
    <%= link_to "住所変更及び新しい住所を登録する", user_address_path(@user.id), class: 'btn btn-primary' %>
  </div>

</div>

app/views/users/index.html.erb

<div class="box">
	<div class="row">
		<strong><div class="search-results"><%= notice %></div></strong>
		<h2> ユーザー一覧</h2>
		<div  class="over_4">
			<table class="table-hover table">
				<thead class="users_index_thread">
					<tr>
						<th class="users_index_thread_th" width="50px"> ID </th>
						<th colspan="2" class="users_index_thread_th" width="150px"> ユーザー名 </th>
						<th class="users_index_thread_th" width="200px"> メールアドレス </th>
						<th colspan="2" class="users_index_thread_th"> </th>
						<th colspan="2" class="users_index_thread_th"> </th>
					</tr>
				</thead>
				<tbody class="test">
					<% @users.each do |user| %>
					<tr>
						<td class="users_index_tbody_td" width="50px"> <%= user.id %> </td>
						<td colspan="2" class="users_index_tbody_td" width="150px"> <%= link_to "#{user.last_name}" + "#{user.first_name}", user_path(user.id) %> </td>
						<td class="users_index_tbody_td" width="200px"> <%= user.email %> </td>
						<td colspan="2"> <%= link_to "編集", edit_user_path(user.id), class: 'btn btn-success' %> </td>
						<td colspan="2"> <%= link_to "退会", user_path(user.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "本当に退会させますか？" %> </td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="box">
  <!-- <div class="message"></div> -->
  <p class="update"><%= notice %></p><p class="alert"><%= alert %></p>
  <div class="users_show_upper clearfix" >
    <div class="users_show_left">
      <h4 class="users_names"> <strong> ユーザー名 </strong> </h4>
      <div> <%= @user.last_name %> <%= @user.first_name %> さん </div>
      <div> <%= link_to "編集", edit_user_path(@user.id), class: 'btn btn-success btn-user-show' %> </div>
      <div> <%= link_to "登録住所を確認する", user_address_path(@user.id), class: 'btn btn-info btn-user-show' %> </div>
      <div> <%= link_to "退会", user_path, class: 'btn btn-danger btn-user-show', method: :'delete', "data-confirm" => "本当に退会しますか？" %> </div>
    </div>
    <div class="users_show_right">
      <h4 class="favorite_artists"> <strong> お気に入りアーティスト </strong> </h4>
      <% if @user.artist_id.nil? %>
        <p> お気に入りアーティストは未登録です </p>
      <% end %>
      <% unless @user.artist_id.nil? %>
      <div>
        <% if @user.artist_id == @user.artist.id %> <%=link_to "#{@user.artist.artist_name}", artist_path(@user.artist) %>
        <% end %>
      </div>
      <div> <%= link_to artist_path(@user.artist) do %><%= attachment_image_tag @user.artist, :artist_image, :fill, 150, 150, format: "jpg" %><% end %> </div>
        <span>
          <strong> 最新のCD： </strong>
        </span>
        <span>
          <% @item.each do |item| %> <%= link_to "#{item.item_name}", item_path(item) %>
          <% end %>
        </span>
        <div>
          <span>ジャンル：</span>
          <% @genre.each do |genre| %> <%= @user.artist.genre.genre_name %>
          <% end %>
        </div>
        <%# if @user.item_id == genre.id %> <%#= genre.genre_name %>
        <div>
          <span>価格：￥</span>
          <% @item.each do |item| %> <%= number_with_delimiter(item.price) %>
        </div>
        <div>
          <% @item.each do |item| %>
          <%= link_to item_path(item) do %><%= attachment_image_tag item, :item_image, :fill, 150, 150, format: "jpg" %><% end %>
          <% end %>
        </div>
      <% end %><% end %>
    </div>
    <div class="users_show_right_right">
      <h4 class="favorite_ranking"> <strong> いいねランキング </strong> </h4>
      <table  class="table-hover table">
        <tbody>
          <% @rank.each.with_index(1) do |rank, i| %>
          <tr>
            <td><%= "#{i}位" %></td>
            <td><%= link_to item_path(rank.id) do %><%= attachment_image_tag rank, :item_image, :fill, 50, 50, format: 'jpeg' %><% end %></td>
            <td><span> <%= link_to "#{rank.item_name}", item_path(rank) %> </span><br><span>価格：￥<%= number_with_delimiter(rank.price) %></span></td>
            <td><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><%= rank.likes.count %></td>
            <td><%= form_for (@cart_item), url: carts_add_item_path(rank.id) do |f| %><span>数量</span><%= f.number_field :units ,min:0 %><%= f.submit 'カートに入れる' %><% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% if @purchases.exists? %>
    <div class="users_show_bottom">
      <div class="container">
        <div class="row">
          <div class="">
            <h4 class="purchase_histories">  <strong> 購入履歴 </strong> </h4>
          </div>
        </div>
      </div>
    </div>
      <% n = 1 %>
      <% @purchases.each do |purchase| %>
    <div class="panel-group" id='sampleAccordion<%= n %>'>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <a data-toggle="collapse" data-parent='#sampleAccordion<%= n %>' href='#sampleAccordionCollapse<%= n %>'>
              ▼<%= purchase.purchased_date.strftime('%Y/%m/%d') %>
            </a>
          </h3>
        </div>
        <div id='sampleAccordionCollapse<%= n %>' class="panel-collapse collapse">
          <% purchase.purchase_datails.each do |datail| %>
          <div class="panel-body">
            <div class="container">
              <div class="row">
                <div class="col-md-2" style="">
                  <%= attachment_image_tag datail.item, :item_image, :fill, 50, 50, format: 'jpeg' %>
                </div>
                <div class="col-md-2" style="">
                  アーティスト名：<%= link_to datail.item.artist.artist_name, artist_path(datail.item.artist.id) %><br>
                  商品名：<%= link_to datail.item.item_name, item_path(datail.item) %>
                </div>
                <div class="col-md-2" style="">
                  単価：<%= number_with_delimiter(datail.price) %>円<br>
                  数量：<%= datail.quantity %>
                </div>
                <div class="col-md-3" style="">
                  <% user_comment = 0 %>
                  <% datail.item.reviews.each do |review| %>
                    <% if review.user_id == @user.id %><% user_comment = 1 %>
                      <%= review.comment %><br>
                      <%= review.created_at.strftime('%Y/%m/%d') %>
                      <% if review.user == current_user %>
                        <%= link_to item_review_path(review.item,review), method: :delete, "data-confirm" => "本当に削除しますか？" do %><button class="">削除</button><br><% end %>
                      <% end %></p>
                    <% end %>
                  <% end %>
                  <% unless admin_signed_in? %>
                    <% if user_comment == 0 %>
                      <%= form_for [datail.item, @review] do |f| %>
                        <%= f.text_area :comment, rows:'5', class: "",placeholder: "レビューを入力してください" %>
                        <%= f.submit "送信する", class: "" %>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>
                <div class="col-md-3" style="">
                  小計：<%= number_with_delimiter(datail.quantity * datail.price) %>円
                </div>
              </div>
            </div>
          </div>
          <% end %>
            <div class="container">
              <div class="row">
                <div class="col-md-6" style=""></div>
                <div class="col-md-6" style="">
                  <% a = purchase.delivery_address.split(",") %>
                  <!-- .split(",")でdelivery_address内の文字列を,で区切った配列を作りaに入れています -->
                  ご指定の配送先<br>〒<%= a[0] %><br>住所：<%= a[1] %><br>宛名：<%= a[2] %>様宛
                      <!-- a[n]で配列の中のn番目の情報を取り出して下さいと指定しています -->
                </div>
              </div>
            </div>
            <div class="container">
              <div class="row">
                <div class="col-md-9" style=""></div>
                <div class="col-md-3" style="">
                  <div class="border">
                    合計：<%= number_with_delimiter(purchase.total_price) %>円(税込)
                    配送状況：<%= purchase.status %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% n += 1%>
      <% end %>
  <% end %>
</div>