config/routes.rb
Rails.application.routes.draw do
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'items#index'

  get 'carts/register'
  get 'carts/delete_all'
  post 'carts/:item_id/add_item' => 'carts#add_item', as: :carts_add_item #item_idをurlに含めて送信
  patch 'carts/:item_id/update_item' => 'carts#update_item', as: :carts_update_item
  delete 'carts/:item_id/delete_item' => 'carts#delete_item', as: :carts_delete_item
  # get 'carts/confirmation'
  get 'artists/admin_index'
  # get 'items/admin_index'
  patch 'users/:id/favorite' => 'users#favorite', as: :user_favorite
  # get 'purchase/:purchase_id/confirmation' => 'purchase_datails#confirmation', as: :confirmation

  resources :users, only: [:show, :edit, :update, :index, :destroy]do
    resources :addresses, only: [:new, :create, :edit, :show, :update, :destroy]
    resource :carts, only: [:show]
  end

  delete '/users/:id' => 'users#destroy'

  resources :artists

  resources :items do
    resource :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    resources :disks, only: [:new, :create, :index, :destroy]do
      resources :songs, only: [:new, :create, :edit, :update, :index, :destroy]
    end
  end

  resources :purchases, only: [:create, :update, :index]do
    resource :purchase_datails, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	has_many :cart_items, dependent: :destroy

	validates :user_id, uniqueness: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!
	before_action :setup_cart_item!, only: [:add_item, :update_item, :delete_item]
	before_action :reset_session_url!, only: [:add_item, :show]

	def show
	  @cart_items = current_cart.cart_items
	  unless Address.exists?(user_id: current_user.id)
	    redirect_to new_user_address_path(current_user)
	    flash[:notice]="住所を登録して下さい" and return
	  end
	end


	# 「カートに入れる」を押した時のアクション
	def add_item
	  item = Item.find(params[:item_id])
	  if cart_item_params[:units].to_i <= 0
	    redirect_to item_path(item)
		flash[:alert]="数量が正しくありません" and return
	  end
	  if @cart_item.nil? #setup_cart_item!の結果がnilかどうか聞いています。nilなら新しいcart_itemを作ります。
	    cart_item = CartItem.new(cart_item_params)
	    if cart_item.units > item.inventory
	      redirect_to item_path(item)
		  flash[:alert]="申し訳ありませんが在庫以上のご注文は承ることができません" and return
		else
	  	  cart_item.item_id = item.id
	  	  cart_item.cart_id = current_cart.id
	  	  cart_item.save
	  	end
	  else               #nilでなければ同じ商品がカートに入っているということなので数量を足します
	   	additem = CartItem.new(cart_item_params)
	   	if additem.units + @cart_item.units > item.inventory
	   	  redirect_to user_carts_path(current_user)
		  flash[:alert]="申し訳ありませんが在庫以上のご注文は承ることができません" and return
		else
          @cart_item.units += additem.units
          @cart_item.save
        end
	  end
	  unless session[:url].blank?
	  	session[:url] = nil
	  end
	  redirect_to user_carts_path(current_user)
	end

	# カート画面で「この数量で更新」を押した時のアクション
	def update_item
      if cart_item_params[:units].to_i == 0
      	@cart_item.destroy
        redirect_to user_carts_path(current_user)
	    flash[:notice]="商品を戻しました"
	  elsif cart_item_params[:units].to_i > @cart_item.item.inventory
	  	redirect_to user_carts_path(current_user)
		flash[:alert]="申し訳ありませんが在庫以上のご注文は承ることができません"
	  else
	    if @cart_item.update(cart_item_params)
	      redirect_to user_carts_path(current_user), notice: "更新しました！"
	    else
	      @cart_items = current_cart.cart_items
	  	  flash.now[:alert] = "数量が正しくなかったため更新できませんでした"
	  	  render :show
	    end
	  end
	end

	 # カート画面で「削除」を押した時のアクション
	def delete_item
	  @cart_item.destroy
	  redirect_to user_carts_path(current_user)
	  flash[:notice]="商品を戻しました"
	end

	def delete_all
	  cart_items = current_cart.cart_items
	  cart_items.delete_all
	  redirect_to user_carts_path(current_user)
	  flash[:notice]="カートを空にしました"
	end

	def register
	  @purchase = Purchase.new
	  @sum = 0 #計算用のsumという変数(sumという名前じゃなくても良いです)の値を0に設定(初期化)しておきます
	  cart_items = current_cart.cart_items
	  cart_items.each do |cart_item|
	  	@sum += cart_item.units * cart_item.item.price #cart_itemを１つずつ取り出して小計を計算しsum(合計)に足しています
	  end
	end

	private

	def setup_cart_item!
      # カートの中に入っている商品をitem_idで検索して代入しています。item_idと一致する商品が見つからない場合はnilが代入されます。
	  @cart_item = current_cart.cart_items.find_by(item_id: params[:item_id])
	end

	def reset_session_url!
	  session[:url] = nil
	end

	def cart_item_params
	  params.require(:cart_item).permit(:cart_id, :item_id, :units)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/register.html.erb
<div class="register">
  <div class="register-box">
    <label class="register-title">お届け先の選択</label><br>
    <small>ご希望の宛先にチェックを入れて下さい</small>
  </div>
  <%= form_for (@purchase), url: purchases_path do |f| %>
    <% boolean = true %>
　  <% n = 1 %>
　  <% current_user.addresses.each do |address| %>
    <% delivery_address = address.postal_code+","+address.address+","+address.address_name %>
    <!-- 郵便番号,住所,宛名をまとめてdelivery_addressに入れています。,を境に入れているのはあとで使いやすくするためです。 -->
    <div class="field register-delivery-box">
      <label><%= f.radio_button :delivery_address, delivery_address, {:checked => boolean } %><strong>宛先<%= n %></strong></label><br>
      <div class="register-delivery-content">
      <%= f.label :宛名 %>：<%= f.label :"#{address.address_name}" %><br/>
      <%= f.label :郵便番号 %>：<%= f.label :"#{address.postal_code}" %><br/>
      <%= f.label :住所 %>：<%= f.label :"#{address.address}" %><br/>
      </div>
    </div>
    <% n += 1 %>
    <% if n ==  2 %>
      <% boolean = false %>
    <% end %>
    <% end %>
    <div class="register-footer">
      <%= link_to "お届け先を追加される方はこちらから", user_address_path(current_user, current_user.addresses.first) %><br>

      合計<%= number_with_delimiter(@sum) %>円

      <% taxincl = @sum * 1.08 %>

      <span class="register-taxincl">(税込<%= number_with_delimiter(taxincl.round) %>円)</span><br>

      <!-- このボタンを押すとpurchasesコントローラーのcreateが実行されます -->



      <div><%= link_to user_carts_path(current_user) do %><button class="btn btn-default btn-info btn-register">カートに戻る</button><% end %><br><%= f.submit '購入確定', class:"comfirm" %><br></div>
    </div>
  <% end %>
</div>

app/views/carts/show.html.erb
<div class="box">
<% sum = 0 %>
<h1>あなたのカート</h1>
<% if @cart_items.count == 0 %>
<p class="update"><%= notice %></p><p class="alert"><%= alert %></p><br>
カートに入っている商品はありません<br>
<%= link_to items_path do %><button class="btn-sm">商品一覧へ</button><% end %>


<% else %>
<p class="update"><%= notice %></p><p class="alert"><%= alert %></p>
<table  class="table-hover table">
  <tbody>
        <thead>
          <tr>
            <th></th>
            <th><h4>商品名</h4></th>
            <th><h4>在庫</h4></th>
            <th><h4>価格</h4></th>
            <th><h4>注文数量</h4></th>
            <th></th>
            <th><h4>小計</h4></th>
          </tr>
        </thead>
        <% @cart_items.each do |ci| %>
        <tr  class="cart_item_box">
          <td><%= link_to item_path(ci.item.id) do %><%= attachment_image_tag ci.item, :item_image, :fill, 100, 100, format: 'jpg' %><% end %><br></td>
          <td><%= ci.item.item_name %></td>
          <td><%= ci.item.inventory %></td>
          <td>¥<%= number_with_delimiter(ci.item.price) %></td>
          <td><%= form_for (ci), url: carts_update_item_path(ci.item.id) do |f| %>
          <%= f.label :"数量を変える(現在の数量が表示されています)" %><br>
          <%= f.number_field :units, min:0 %>
          <%= f.submit 'この数量で更新' %><br></td>
              <% end %>
          <td><%= link_to carts_delete_item_path(ci.item.id), method: :delete, "data-confirm" => "全ての#{ci.item.item_name}をカートから外しますか？" do %>
          <button class="btn-sm btn-default btn-danger">削除</button><% end %></td>
          <td>(<%= ci.units %>点)¥ <%= number_with_delimiter(ci.units * ci.item.price) %>円</td>
          <!-- 合計を出す準備の計算です -->
          <% sum = ci.units * ci.item.price + sum %>
        </tr>
          <% end %>
      <br>
  </tbody>
</table>
<div class="container">
  <div class="row">
    <div class="col-md-8" style=""></div>
    <div class="col-md-4" style="">
      合計<%= number_with_delimiter(sum) %>円
      <% taxincl = sum * 1.08 %>
      (税込 <span  class="price"><%= number_with_delimiter(taxincl.round) %>円</span>)<br>
<%= link_to items_path do %><button class="btn-sm">買い物を続ける</button><% end %>
<%= link_to carts_register_path do %><button class="btn-sm">レジに進む</button><% end %>
<%= link_to carts_delete_all_path, "data-confirm" => "全ての商品をカートから外しますか？"  do %><button class="btn-sm">全ての商品を戻す</button><% end %>
    </div>
  </div>
</div>
<% end %>
</div>