config/routes.rb
Rails.application.routes.draw do
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  root 'items#index'

  get 'carts/register'
  get 'carts/delete_all'
  post 'carts/:item_id/add_item' => 'carts#add_item', as: :carts_add_item #item_idをurlに含めて送信
  patch 'carts/:item_id/update_item' => 'carts#update_item', as: :carts_update_item
  delete 'carts/:item_id/delete_item' => 'carts#delete_item', as: :carts_delete_item
  # get 'carts/confirmation'
  get 'artists/admin_index'
  # get 'items/admin_index'
  patch 'users/:id/favorite' => 'users#favorite', as: :user_favorite
  # get 'purchase/:purchase_id/confirmation' => 'purchase_datails#confirmation', as: :confirmation

  resources :users, only: [:show, :edit, :update, :index, :destroy]do
    resources :addresses, only: [:new, :create, :edit, :show, :update, :destroy]
    resource :carts, only: [:show]
  end

  delete '/users/:id' => 'users#destroy'

  resources :artists

  resources :items do
    resource :likes, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
    resources :disks, only: [:new, :create, :index, :destroy]do
      resources :songs, only: [:new, :create, :edit, :update, :index, :destroy]
    end
  end

  resources :purchases, only: [:create, :update, :index]do
    resource :purchase_datails, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	acts_as_paranoid

	belongs_to :artist
	belongs_to :label, optional: true
	belongs_to :genre, optional: true
	has_many :disks, dependent: :destroy
	has_many :purchase_datails
	has_many :cart_items
	has_many :likes, dependent: :destroy
	has_many :reviews, dependent: :destroy

	validates :artist_id, presence: true
	validates :label_id, presence: true
	validates :genre_id, presence: true
	validates :item_image, presence: true
	validates :item_name, presence: true
	validates :item_contents, presence: true
	validates :price, numericality: { only_integer: true }
	validates :inventory, numericality: { only_integer: true }

	# validates :disk_number, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
	# validates :price, numericality: { only_integer: true }


	attachment :item_image

	# 絞り込み検索時に使用するデータ（seedに入っているIDと内容を同じにすると使えるっぽい）
	enum genre: { JｰPOP: 1, 洋楽: 2, レゲエ: 3, ロック: 4, トランス: 5, アニメソング: 6, EDM: 7, 演歌: 8 }
	enum label: { エイベックス: 1, ソニーミュージック: 2, ポニーキャニオン: 3, テレビ朝日ミュージック: 4, ユニバーサルミュージック: 5, ワーナーミュージックジャパン: 6 }#, その他: 7 }

	# スコープでセレクトタグによって指定したIDをもとにwhereで絞り込みしてるみたいです。。
	scope :get_by_genre_id, ->(genre_id) { where(genre_id: genre_id) }
	scope :get_by_label_id, ->(label_id) { where(label_id: label_id) }

	# 名による絞り込み
	scope :get_by_item_name, ->(item_name) { where("item_name like ?", "%#{item_name}%") }
	# 性別による絞り込み
	# scope :get_by_gender, ->(gender) { where(gender: gender) }

	def favorited_by?(user)
          likes.where(user_id: user.id).exists?
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


	def index
	  @items = Item.all
	  @item = Item.new
	  @artists = Artist.all
	  @genres = Genre.all
	  @labels = Label.all
	  @review = Review.all
	  @likes = Like.all
	  @rank = Item.find(Like.group(:item_id).order('count(item_id) desc').limit(20).pluck(:item_id))

	  if params[:genre_id].present?
		@items = @items.get_by_genre_id params[:genre_id]
	  end
	  if params[:label_id].present?
		@items = @items.get_by_label_id params[:label_id]
	  end
	  if params[:item_name].present?
		@items = @items.get_by_item_name params[:item_name]
	  end

	  unless @items.count == Item.all.count
	  # itemsの数がitems.allから変わっているか確認する
		if @items.count == 0
		# itemsの数が０の時
		  @items = Item.all
		  flash.now[:notice] = "ヒットしませんでした。検索ワードを変えてみて下さい。"
		  render :action => :index, layout: "item" and return
		  # indexに戻りitemのレイアウトを適用させる。renderをもう一度使いたいためreturnする。
		elsif @items.count > 0
          flash.now[:notice] = "#{@items.count}件のCDがヒットしました。"
          #{@items.count}で絞り込まれた数を表示させる
          render :action => :index, layout: "item" and return
          # renderにする事で変更された情報を維持しつつnoticeを表示させる
		end
	  end

		 #render :index, layout: "item"
		# itemのレイアウトを適用させる。


      if user_signed_in?
	    if current_user.last_sign_in_at == current_user.current_sign_in_at
		  if Address.exists?(user_id: current_user.id)
		  	unless session[:url].blank?
		  	  redirect_to session[:url] and return
		  	end
		  else
			redirect_to new_user_address_path(current_user)
			flash[:notice]="住所を登録して下さい" and return
          end
        else
          unless session[:url].blank?
		  	redirect_to session[:url] and return
		  end
        end
	  end

    end

	def new
		if admin_signed_in?
			@item = Item.new
			@items = Item.all
			@artists = Artist.all
			# @genres = Genre.all
			# @labels = Label.all
	
			if params[:genre_id].present?
				@items = @items.get_by_genre_id params[:genre_id]
			end
			if params[:label_id].present?
				@items = @items.get_by_label_id params[:label_id]
			end
			if params[:item_name].present?
				@items = @items.get_by_item_name params[:item_name]
			end
	
			unless @items.count == Item.all.count
				# itemsの数がitems.allから変わっているか確認する
			if @items.count == 0
				# itemsの数が０の時
				@items = Item.all
				flash.now[:notice] = "ヒットしませんでした。検索ワードを変えてみて下さい。"
				render :action => :new, layout: "item_new" and return
				# newに戻りitem_newのレイアウトを適用させる。renderをもう一度使いたいためreturnする。
			elsif @items.count > 0
	
        	  	flash.now[:notice] = "#{@items.count}件のCDがヒットしました。"
        	  	#{@items.count}で絞り込まれた数を表示させる
	
        	  	render :action => :new, layout: "item_new" and return
        	  	# renderにする事で変更された情報を維持しつつnoticeを表示させる
			end
			end
	
			render :new, layout: "item_new"
		else
			redirect_to items_path
		end
	end

	def create
		@item = Item.new(item_params)
		if @item.save
			redirect_to item_disks_path(@item.id)
			flash[:notice]="商品の登録ができました"
		else
			@items = Item.all
			render :new
		end
	end

	def show
		@item = Item.find(params[:id])
		@review = Review.new
		@artists = Artist.all
		@genres = Genre.all
		@labels = Label.all
		@disks = Disk.all
		@songs = Song.all
		@cart_item =CartItem.new
		@likes = Like.all
		@rank = Item.find(Like.group(:item_id).order('count(item_id) desc').limit(20).pluck(:item_id))

		unless user_signed_in?
		  session[:url] = request.url
		end


	end


	# def admin_index
	# 	if admin_signed_in? 
	# 		@items = Item.all
	# 		@item = Item.new
	# 		@artists = Artist.all
	# 		@genres = Genre.all
	# 		@labels = Label.all
	# 		if params[:genre_id].present?
	# 			@items = @items.get_by_genre_id params[:genre_id]
	# 		end
	# 		if params[:label_id].present?
	# 			@items = @items.get_by_label_id params[:label_id]
	# 		end
	# 		if params[:item_name].present?
	# 			@items = @items.get_by_item_name params[:item_name]
	# 		end
	
	# 		unless @items.count == Item.all.count
	# 			# itemsの数がitems.allから変わっているか確認する
	# 		if @items.count == 0
	# 			# itemsの数が０の時
	# 			@items = Item.all
	# 			flash.now[:notice] = "ヒットしませんでした。検索ワードを変えてみて下さい。"
	# 			render :action => :admin_index, layout: "admin_item" and return
	# 			# admin_indexに戻りadmin_itemのレイアウトを適用させる。renderをもう一度使いたいためreturnする。
	# 		elsif @items.count > 0
	
 #        	  	flash.now[:notice] = "#{@items.count}件のCDがヒットしました。"
 #        	  	#{@items.count}で絞り込まれた数を表示させる
	
 #        	  	render :action => :admin_index, layout: "admin_item" and return
 #        	  	# renderにする事で変更された情報を維持しつつnoticeを表示させる
	# 		end
	# 		end
	# 		render :admin_index, layout: "admin_item" and return
	# 		# admin_itemのレイアウトを適用させる。
	# 	else
	# 		redirect_to items_path and return
	# 	end 
	# end

	def edit
		if admin_signed_in? 
			@item = Item.find(params[:id])
			# @artists = Artist.find(params[:id])
			# @genres = Genre.find(params[:id])
			# @labels = Label.find(params[:id])
		else
			redirect_to items_path
		end
	end


	def update
		@item = Item.find(params[:id])
		@item.update(item_params)
		redirect_to new_item_path
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to new_item_path
	end

	private
	def item_params
		params.require(:item).permit(:item_name, :artist_id, :genre_id, :price, :inventory, :item_contents, :label_id, :item_image)
	end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/admin_index.html.erb
  <div class="box">
    <div class="row">
      <strong><div class="search-results"><%= notice %></div></strong>
        <h2>商品検索</h2>
        <div  class="over_4">
          <table  class="table-hover table">
            <thead>
              <tr>
                <th>ジャケ写</th>
                <th>商品名</th>
                <th>アーティスト</th>
                <th>ジャンル</th>
                <th>レーベル</th>
                <th>価格</th>
                <th>在庫</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
              <% @items.each do |item| %>
                <td><%= link_to item_path(item) do %><%= attachment_image_tag item, :item_image, :fill, 50, 50, format: 'jpeg' %><% end %></td>
                <td><%= link_to item_path(item.id) do %><%= item.item_name %><% end %></td>
                <td><%= link_to artist_path(item.artist.id) do %><%= item.artist.artist_name %><% end %></td>
                <td><%= item.genre.genre_name %></td>
                <td><%= item.label.label_name %></td>
                <td><%= number_with_delimiter(item.price) %></td>
                <td><%= item.inventory %></td>
                <td><%= link_to edit_item_path(item.id) do %><button class="btn btn-default btn-success">編集</button><% end %></td>
                <td><%= link_to item_path(item.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %><button class="btn btn-default btn-danger">削除</button><% end %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>

app/views/items/edit.html.erb
<div  class="container">
  <div class="row">
    <h1  class="artist_edit_headline">商品情報変更</h1>

    <div  class="box2">

    <%= attachment_image_tag @item, :item_image, :fill, 200, 200, format: 'jpeg' %>

    <%= form_for(@item) do |f| %>

    <%= f.label :"シングル/アルバム名" %><br>
    <%= f.text_field :item_name, class:"data" %><br>

    <%= f.label :"商品説明" %><br>
    <%= f.text_area :item_contents, class:"data" %><br>

    <%= f.label :"アーティスト" %><br>
    <%= f.select :artist_id,Artist.all.collect { |p| [ p.artist_name, p.id ] }, {include_blank: true}, {class: 'data'} %><br>

    <%= f.label :"ジャンル" %><br>
    <%= f.select :genre_id,Genre.all.collect { |p| [ p.genre_name, p.id ] }, {include_blank: true}, {class: 'data'} %><br>

    <%= f.label :"レーベル" %><br>
    <%= f.select :label_id,Label.all.collect { |p| [ p.label_name, p.id ] }, {include_blank: true}, {class: 'data'} %><br>

    <%= f.label :"ジャケット写真" %><br>
    <%= f.attachment_field :item_image, placeholder:"ジャケット画像", class:"data" %><br>
    <!-- f.submit class:"btn btn-primary item_data" -->

    <%= f.label :"価格（税抜き）" %><br>
    <%= f.text_field :price, class:"data" %><br>

    <%= f.label :"在庫" %><br>
    <%= f.text_field :inventory, class:"data" %><br>

    <%= f.submit '上記の内容で変更する', class:"btn btn-success active data" %>

    <% end %>

    <p><button  class="btn btn-warning data"><%= link_to "DISK編集", item_disks_path(@item.id) %></button></p>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<header class="header">
  <div class="input-group">
      <%= form_tag(items_path, method: "get") do %>
      <%= label_tag :item_name, "シングル/アルバム名" %><%= text_field_tag :item_name, params[:item_name] %>
      <%= label_tag :ジャンル, "ジャンル" %>
      <%= select_tag :genre_id, options_for_select(Item.genres), include_blank: true %>
      <%= label_tag :"レーベル" %>
      <%= select_tag :label_id, options_for_select(Item.labels), include_blank: true %>
      <%= button_tag( class: " btn-primary") do %>
      <%= content_tag :span, "", class: "glyphicon glyphicon-search" %>
      <% end %>
      <% end %>
  </div>
</header>



<div class="box">
  <div class='row'>
    <strong><div class="search-results"><%= notice %></div></strong>
    <div class="col-lg-8">
      <h1> CD一覧</h1>
      <div class="over_1 clearfix">
        <% @items.each do |item| %>
        <div class="item-box directory">
          <dl>
            <dt><%= link_to item_path(item.id) do %><%= attachment_image_tag item, :item_image, :fill, 100, 100, format: 'jpeg' %><% end %></dt>
            <dd><h4><%= link_to item_path(item.id) do %><%= item.item_name %><% end %></h4></dd>
            <dd><% @artists.each do |artist| %><%= link_to artist_path(artist.id) do %><% if item.artist_id == artist.id %><%= artist.artist_name %><% end %><% end %><% end %></dd>
            <dd><% @genres.each do |genre| %><% if item.genre_id == genre.id %><%= genre.genre_name %><% end %><% end %></dd>
            <dd><% @labels.each do |label| %><% if item.label_id == label.id %><%= label.label_name %><% end %><% end %></dd>
            <dd>￥<%= number_with_delimiter(item.price) %></dd>
          </dl>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-4">
        <h3> CDいいねランキング</h3>
        <div class="over_3">
        <table  class="table-hover table">
          <tbody>
            <% @rank.each.with_index(1) do |rank, i| %>
            <tr>
              <td><%= "#{i}位" %></td>
              <td><%= link_to item_path(rank.id) do %><%= attachment_image_tag rank, :item_image, :fill, 50, 50, format: 'jpeg' %><% end %></td>
              <td><%= link_to "#{rank.item_name}", item_path(rank) %><br>価格：￥<%= number_with_delimiter(rank.price) %></td>
              <td><% @artists.each do |artist| %><% if rank.artist_id == artist.id %><%= link_to "#{artist.artist_name}", artist_path(artist) %><% end %><% end %></td>
              <td><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><%= rank.likes.count %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
  <div class="box">
    <div class="row">
      <strong><div class="search-results"><%= notice %></div></strong>
      <div  class="col-md-4 col-sm-4">
      <h3> 商品登録</h3>
      <div class="box2">
        <% if @item.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2  class="alert_h2"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <%= form_for(@item) do |f| %>

        <%= f.label :"アーティスト" %><br>
        <%= f.select :artist_id,Artist.all.collect { |p| [ p.artist_name, p.id ] }, {include_blank: true}, {class: 'data'} %><br>

        <%= f.label :"ジャンル" %><br>
        <%= f.select :genre_id,Genre.all.collect { |p| [ p.genre_name, p.id ] }, {include_blank: true}, {class: 'data'} %><br>

        <%= f.label :"レーベル" %><br>
        <%= f.select :label_id,Label.all.collect { |p| [ p.label_name, p.id ] }, {include_blank: true}, {class: 'data'} %><br>

        <%= f.label :"ジャケット写真" %><br>
        <%= f.attachment_field :item_image, placeholder:"ジャケット画像", class:"data" %><br>

        <%= f.label :"シングル/アルバム" %><br>
        <%= f.text_field :item_name, class:"data" %><br>

        <%= f.label :"商品説明" %><br>
        <%= f.text_area :item_contents, class:"data" %><br>

        <%= f.label :"価格（税抜き）" %><br>
        <%= f.text_field :price, class:"data" %><br>

        <%= f.label :"在庫" %><br>
        <%= f.text_field :inventory, class:"data" %><br>

        <p><%= f.submit '上記の内容で登録する', class:"btn btn-success active data" %></p>

        <% end %>
      </div>

      </div>
      <div class="col-md-8 col-sm-8">
        <h1> CD一覧</h1>
        <div  class="over_2">
          <table  class="table-hover table">
            <thead>
              <tr>
                <th>ジャケ画像</th>
                <th>アルバム/シングル<br>(<small>アーティスト</small>)</th>
                <th>商品説明</th>
                <th>価格</th>
                <th>在庫</th>
                <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @items.each do |item| %>
              <tr>
                <td><%= link_to item_path(item) do %><%= attachment_image_tag item, :item_image, :fill, 50, 50, format: 'jpeg' %><% end %></td>
                <td><%= link_to item.item_name, item_path(item) %><br>(<small><%= link_to item.artist.artist_name, artist_path(item.artist) %></small>)</td>
                <td><%= item.item_contents %></td>
                <td><%= number_with_delimiter(item.price) %></td>
                <td><%= item.inventory %></td>
                <td><%= link_to edit_item_path(item.id) do %><button class="btn btn-default btn-success">編集</button><% end %></td>
                <td><%= link_to item_path(item.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %><button class="btn btn-default btn-danger">削除</button><% end %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="box">
	<div class='row'>
		<div class="col-md-8">
			<div  class="clearfix">
				<div class="artist_profile_box  clearfix">
					<%= attachment_image_tag @item, :item_image, :fill, 250, 250, format: 'jpeg', class: "artist_show_image" %>
					<div  class="item_contents">


						<h1><%= @item.item_name %></h1>
						<h4>
							・<%= link_to @item.artist.artist_name, artist_path(@item.artist) %>
							<span  class="artist_tag"><%= @item.genre.genre_name %></span>
							<span  class="artist_tag"><%= @item.label.label_name %></span>
						</h4>
						<p>・価格　¥<%= number_with_delimiter(@item.price) %></p>
						<p>・在庫　<%= @item.inventory %></p>
						<% if @item.inventory == 0 %>
						<p>・売り切れ：申し訳ありません！<br>・次回の入荷までお待ちください</p>
						<% elsif @item.inventory <= 5 %>
						<p>・☆人気の商品です☆
							<% if @item.inventory == 1 %>
							・残り１個です！お早めに！</p>
							<% else %>
						・在庫残りわずかにつきお早めに!</p>
						<% end %>
						<% end %>

						<% if user_signed_in? %>
							<% if @item.favorited_by?(current_user) %>
								<%= render 'likes/like_destroy' %>
								<% else %>
								<%= render 'likes/like_create' %>
							<% end %>
							<% else %>
								<p>・いいね<%= @item.likes.count %></p>
						<% end %>
						<% if @item.inventory == 0 %>
						<% else %>
						<%= form_for (@cart_item), url: carts_add_item_path(@item.id) do |f| %>
						<%= f.label :"・数量を選ぶ" %>
						<%= f.number_field :units, min:0 %>
						<%= f.submit 'カートに入れる' %><br>
						<% end %>
						<% end %>
						<p class="alert"><%= alert %></p>
						<div  class="item_contents_box directory">
							<p>・Description<br><%= @item.item_contents %></p>
						</div>
					</div>
				</div>

				<% @disks.each.with_index(1) do |disk,i| %>
				<% if @item.id == disk.item_id %>
				<button type="button" class="btn btn-default btn-block">
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#faq" href="#faqpost_<%= "#{i}" %><%= @item.id %><%= disk.id %>">ディスク<%= disk.disk_number %></a>
						</div>
						<div id="faqpost_<%= "#{i}" %><%= @item.id %><%= disk.id %>" class="accordion-body collapse">
							<div class="accordion-inner">
								<ol>
									<% @songs.each do |song| %>
									<% if disk.id == song.disk_id %>
									<li><%= song.song_name %></li>
									<% end %>
									<% end %>
								</ol>
							</div>
						</div>
					</div>
				</button>
				<% end %>
				<% end %>

				<strong><div class="search-results"><%= notice %></div></strong>
				<div class="artist_item_box">
					<div class="directory">
						<% if user_signed_in? %>
						<p>レビュー<%= @item.reviews.count %>件<br>
							<% @item.reviews.each do |review| %>
							<!-- 日付 -->
							<%= review.created_at.strftime('%Y/%m/%d') %>
							<!-- 名前 -->
							<%#= review.user.first_name %><br>
							<!-- コメント -->
							<%= review.comment %><br>
						</p>
								<%# if review.user == current_user %>
									<%#= link_to item_review_path(@item,review), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
										<!-- <button class="">削除</button><br> -->
									<%# end %>
								<%# end %>
							<% end %>

							<%#= form_for [@item, @review] do |f| %>
							<%#= f.text_area :comment, rows:'5', class: "",placeholder: "レビューを入力（購入者のみ表示）" %>
							<%#= f.submit "送信する", class: "" %>
							<%# end %>
						<% elsif admin_signed_in? %>
							<p>
								レビュー<%= @item.reviews.count %>件<br>
								<% @item.reviews.each do |review| %>
								<!-- 日付 -->
								<%= review.created_at.strftime('%Y/%m/%d') %>
								<!-- 名前 -->
								<%= review.user.first_name %><br>
								<!-- コメント -->
								<%= review.comment %><br>
								
								<%= link_to item_review_path(@item,review), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
									<button class="">削除</button><br>
								<% end %>
								<% end %>
							</p>
						<% else %>
							<p>
								レビュー<%= @item.reviews.count %>件<br>
								<% @item.reviews.each do |review| %>
								<%#= review.user.first_name %><br>
		    					
		    					<%= review.created_at.strftime('%Y/%m/%d') %><br>
		    					<%= review.comment %>
		    				</p>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<h3> CDいいねランキング</h3>
			<div class="over_3">
				<table  class="table-hover table">
					<tbody>
						<% @rank.each.with_index(1) do |rank, i| %>
						<tr>
							<td><%= "#{i}位" %></td>
							<td><%= link_to item_path(rank.id) do %><%= attachment_image_tag rank, :item_image, :fill, 50, 50, format: 'jpeg' %><% end %></td>
							<td><%= link_to "#{rank.item_name}", item_path(rank) %><br>価格：￥<%= number_with_delimiter(rank.price) %></td>
							<td><% @artists.each do |artist| %><% if rank.artist_id == artist.id %><%= link_to "#{artist.artist_name}", artist_path(artist) %><% end %><% end %></td>
							<td><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><%= rank.likes.count %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>